# Generated by Django 4.1.1 on 2022-09-17 13:52

import autoslug.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import gym.models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_alter_category_slug_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='date',
            new_name='pub_date',
        ),
        migrations.AddField(
            model_name='blog',
            name='active',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='draft',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title', slugify=gym.models.Blog.custom_slugify, unique_with=['category', 'tag', 'pub_date__month']),
        ),
        migrations.AddField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='blogimages'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='featured',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tag',
            field=models.ManyToManyField(blank=True, to='gym.tag'),
        ),
    ]
