# Generated by Django 4.1.1 on 2022-09-18 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0010_alter_category_options_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='featured',
        ),
    ]
