# Generated by Django 4.1.1 on 2022-09-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0014_blog_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='quote',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
